config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :favorites
    end

    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :chats, only: %i[index show create]

  resources :posts, only: %i[new show create destroy edit update] do
    resource :favorites, only: %i[index create destroy]
    resources :comments, only: %i[create destroy]
  end

  get 'retrieval' => 'posts#retrieval'

  get 'protect' => 'posts#protect'

  get 'search' => 'posts#search'
  # 通知
  resources :notifications, only: [:index]
  delete 'notifications/destroy' => 'notifications#destroy_all'
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  # optional:true nillを許可
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :chat, optional: true

  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  
  def index
    # @notificaations = current_user.passive_notifications
    # すべての通知の中で、visited_idが自分でfalseのものをとってくる
    @notifications = Notification.where(visited_id: current_user.id, cheacked: false)
    # include NotificationsHelper
    # testt = NotificationsHelper::Aaa.unchecked_notifications
    # p testt
    # とってきた通知をtrueにかえる
    # byebug
    # @notificaations.each do |notification|
    #  notification.update_attributes(cheacked: true)
    # end

    # @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    # @notifications.where(checked: false).each do |notification|
    #  notification.update_attributes(checked: true)
    # end
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% visited = notification.visited %>

<div class='m-2'>
  <%= link_to user_path(visiter) do %>
    <span class="visiter_user_image_box"><%= attachment_image_tag visiter, :account_image, class:"visiter_user_image rounded-circle", size: "70x70", fallback: "icon.jpeg" %></span>
    <%= visiter.account_name %>
  <% end %>

  <span>さんが</span>

  <% case notification.action %>
    <% when 'follow' then %>
      <%= "あなたをフォローしました" %>
    <% when 'chat' then %>
      <%= link_to 'あなたにメッセージ', chat_path(notification.visiter), style:"font-weight: bold;", class: "border-bottm" %>
      <%= "を送りました" %>
    <% when 'comment' then %>
      <%= link_to 'あなたの投稿にコメント', post_path(notification.post_id), style:"font-weight: bold;", class: "border-bottom" %>
      <%= "をしました" %>
  <% end %>
  <span><%= "(#{time_ago_in_words(notification.created_at)}前)" %></span><br />
</div>

app/views/notifications/index.html.erb
<!--自分の投稿に対するコメントは表示しない-->
<div class="container p-5">
  <h3 class="font">通知</h3>
  <%= link_to notifications_destroy_path, method: :delete do %>
    <i class="fas fa-trash" style="color: black;"></i>
    <h7 style="color: black;">全削除</h7>
  <% end %>
  <hr>
  <div class="bg-white border rounded">
    <% if @notifications.exists? %>
      <% @notifications.each do |notification| %>
        <%= render notification %>
      <% end %>

    <% else %>
      <p class="nothing">通知はありません</p>
    <% end %>
  </div>
</div>