config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :favorites
    end

    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :chats, only: %i[index show create]

  resources :posts, only: %i[new show create destroy edit update] do
    resource :favorites, only: %i[index create destroy]
    resources :comments, only: %i[create destroy]
  end

  get 'retrieval' => 'posts#retrieval'

  get 'protect' => 'posts#protect'

  get 'search' => 'posts#search'
  # 通知
  resources :notifications, only: [:index]
  delete 'notifications/destroy' => 'notifications#destroy_all'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :last_name, :first_name, :kana_last_name, :kana_first_name, :account_name, :address, :phone_number, :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # フォローされているユーザをフォローしている人
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :follower, source: :followed_user
  # フォローしているユーザをフォローしている人
  has_many :followed_user, class_name: 'Relationship', foreign_key: 'followed_user_id', dependent: :destroy
  has_many :followers, through: :followed_user, source: :follower

  has_many :chats, dependent: :destroy

  # has_many :post_images
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 通知機能 active_notification自分からの通知 passive_notification相手からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # アカウント画像
  attachment :account_image

  def follow(user_id)
    follower.create(followed_user_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_user_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # フォローされたとき通知作成
  def create_notification_follow!(current_user)
    # Notificationのカラムに直接データを指定する
    temp = Notification.where(['visiter_id = ? and visited_id = ? and action = ?', current_user.id, id, 'follow'])
    if temp.blank?
      notification = Notification.new(
        visiter_id: current_user.id,
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  #chatにメッセージがきたときの通知作成
  def create_notification_chat!(current_user)
    temp_ids = Chat.select(:user_id).where(caht_id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_chat!(current_user, chat_id, temp_id['user_id'])
    end
    save_notification_caht!(current_user, chat_id, user_id) if temp_ids.blank?
  end

  def save_notification_chat!(current_user, chat_id, visited_id)
    notification = current_use.active_notifications.new(
      chat_id: chat_id,
      visited_id: visited_id,
      action: 'chat'
    )
    notification.cheacked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def show
    @user = User.find(params[:id])
    @unchecked_notifications = Notification.where(visited_id: current_user.id, cheacked: false)
    @posts = Post.where(user_id: @user).page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = '更新できました'
      redirect_to user_path(user.id)
    else
      render :edit
    end
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
    @unchecked_notifications = Notification.where(visited_id: current_user.id, cheacked: false)
  end

  private

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :kana_last_name, :kana_first_name, :account_name,
                                 :account_image, :address, :phone_number, :introduction)
  end

  def post_params
    params.require(:post).permit(:post_image_id, :text, :plase, :pet_name, :pet_sex)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<!--ユーザ情報-->
<div class="info-contaner border rounded">
  <div class="info">
    <%= attachment_image_tag user, :account_image, size: "100x100", class: 'rounded-circle p-2', fallback: "icon.jpeg" %><br />
    <%= link_to user_path(user), class: 'font' do %>
      <%= user.account_name %>
    <% end %>
    <div>
      <%= user.introduction %>
    </div>
    <div class="font p-3">
      <% if user.id == current_user.id %>
        <%= link_to '編集', edit_user_path(user.id) %><br />
        <%= link_to 'いいね', favorites_user_path(user.id) %><br />
        <% if @unchecked_notifications.any? %>
          <i class="fa fa-circle" style="color: gold;"></i>
        <% end %>
        <%= link_to '通知', notifications_path %><br />
        <%= link_to "フォロー", user_followings_path(user.id) %><br />
        <%= link_to "フォロワー", user_followers_path(user.id) %>


      <% elsif current_user.following?(user) %>
        <% if user.following?(current_user) %>
          <%= link_to "チャット", chat_path(user.id) %><br />
        <% end%>
        <%= link_to "フォローを解除", user_relationships_path(user.id), method: :delete %><br />
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="font p-3">マイページ　編集</h2>
<div class="contener m-5">
  <%= form_with model: @user, local: true do |f| %>

  <table class="table bg-white border rounded">
    <tr>
      <th><%= f.label :"名前" %></th>
      <td><%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"名前", class: 'border rounded' %></td>
      <td><%= f.text_field :first_name, autocomplete: "first_name", class: 'border rounded' %></td>
    </tr>

    <tr>
      <th><%= f.label :"名前（カタカナ）" %></th>
      <td><%= f.text_field :kana_last_name, autocomplete: "kana_last_name", class: 'border rounded' %></td>
      <td><%= f.text_field :kana_first_name, autocomplete: "kana_first_name", class: 'border rounded' %></td>
    </tr>

    <tr>
      <th><%= f.label :"住所" %></th>
      <td colspan="2"><%= f.text_field :address, autocomplete: "address", size: '50x2', class: 'border rounded' %></td>

    </tr>

    <tr>
      <th><%= f.label :"連絡先" %></th>
      <td colspan="2"><%= f.text_field :phone_number, autocomplete: "phone_number", class: 'border rounded' %></td>

    </tr>

    <tr>
      <th><%= f.label :"メールアドレス" %></th>
      <td colspan="2"><%= f.email_field :email, autocomplete: "email", class: 'border rounded' %></td>

    </tr>

    <tr>
      <th><%= f.label :"アカウント名" %></th>
      <td colspan="2"><%= f.text_field :account_name, autocomplete: "account_name", class: 'border rounded' %></td>

    </tr>

    <tr>
      <th><label for="inputimage">アカウント画像</label></th>
      <td>
        <%= attachment_image_tag @user, :account_image, size: '70x70', class: 'border rounded', fallback: "icon.jpeg" %>
      </td>
      <td><%= f.attachment_field :account_image %></td>

    </tr>

    <tr>
      <th><%= f.label :"自己紹介" %></th>
      <td colspan="2"><%= f.text_area :introduction, autofocus: "introduction", size: '60x3', class: 'border rounded' %></td>
    </tr>

  </table>
  <div class="form-group m-5">
    <%= f.submit "保存", class: 'btn btn-info w-25' %>
  </div>

  <% end %>
</div>

app/views/users/favorites.html.erb
<h3 class="font p-3">いいね した投稿一覧</h3>

<div class="container">
  <div class="row">
    <div class="col-4">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-8">
      <%= render 'posts/list', posts: @favorite_posts %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h3 class="font p-3"><%= @user.account_name %> さんのページです</h3>
  <div class="row pb-5">
    <div class="col-4">
      <%= render 'users/info', user: @user %>
    </div>

    <div class="col-8">
      <h4 class="post-btn"><%= link_to new_post_path, class: 'btn btn-light m-2' do %><i class="fas fa-plus-circle"> 投稿する</i><% end %></h4>
      <h4 class="font mt-3">投稿一覧</h4>
      <%= render 'posts/list', posts: @posts %>
    </div>
  </div>
</div>