config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :favorites
    end

    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :chats, only: %i[index show create]

  resources :posts, only: %i[new show create destroy edit update] do
    resource :favorites, only: %i[index create destroy]
    resources :comments, only: %i[create destroy]
  end

  get 'retrieval' => 'posts#retrieval'

  get 'protect' => 'posts#protect'

  get 'search' => 'posts#search'
  # 通知
  resources :notifications, only: [:index]
  delete 'notifications/destroy' => 'notifications#destroy_all'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :category, :animal, :plase, :pet_sex, :text, presence: true
  # デフォルトで作成日時の降順
  default_scope -> { order(created_at: :desc) }

  belongs_to :user

  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :notifications, dependent: :destroy

  # いいねされているか確認するメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # キーワード検索のメソッド
  def self.retrieval(keyword)
    where(["text like? OR  plase like? OR pet_name like?", "%#{keyword}%",  "%#{keyword}%", "%#{keyword}%"])
  end

  # 自分の投稿に自分以外にコメントしている人をすべて取得＋全員(temp_ids)に通知を送る
  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしてないとき、投稿者に通知
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  # コメントが複数回することがあり得るため、1つの投稿に複数回通知＋自分に対するコメントは通知済み
  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    notification.cheacked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end

  # 画像アップする(attachment)為に追加
  # attachment :post_image

  enum pet_sex: {
    オス: 0,
    メス: 1,
    不明: 2
  }

  enum category: {
    捜索中: 0,
    保護中: 1
  }

  enum animal: {
    犬: 0,
    猫: 1,
    その他: 2
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[search protect retrieval]

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @unchecked_notifications = Notification.where(visited_id: current_user.id, cheacked: false)
    @comment = Comment.new
  end

  def create
    # postにuser_idを持たせる必要があるため、current_userを追記
    @post = current_user.posts.create(post_params)

    if @post.save
      flash[:notice] = '投稿できました'
      redirect_to post_path(@post)
    else
      flash[:danger] = '投稿ができませんでした'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = '投稿できました'
      redirect_to post_path(@post)
    else
      flash[:danger] = '投稿ができませんでした'
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    if @post.destroy
      flash[:notice] = '投稿を削除しました'
      redirect_to user_path(@post.user_id)
    else
      flash[:danger] = '投稿の削除に失敗しました'
      redirect_to request referer
    end
  end

  def search
    @posts = Post.where(category: 0).page(params[:page]).per(12)
    @keyword = params[:keyword]
  end

  def protect
    @posts = Post.where(category: 1).page(params[:page]).per(12)
    @keyword = params[:keyword]
  end

  def retrieval
    @posts = Post.retrieval(params[:keyword])

    @search_posts = @posts.where(category: 0).page(params[:page]).per(5)
    @protect_posts = @posts.where(category: 1).page(params[:page]).per(5)

    @keyword = params[:keyword]
  end

  private

  def post_params
    params.require(:post).permit(
      :text,
      :pet_name,
      :plase,
      :pet_sex,
      :category,
      :animal,
      :id,
      post_images_images: []
    )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_list.html.erb
<!--投稿一覧内容-->
  <div class="row">
    <% if posts.present? %>
      <% posts.each do |post| %>
      <div class="card" style="width:20rem">
        <img class="card-img-top">
        <%= attachment_image_tag post.post_images[0], :image, class: 'rounded', size: '10rem', fallback: "logo.jpg", class: 'card-img-top' %>

        <div class="card-body">
          <h5 class="card-title"><%= post.category %> / <%= post.plase %></h5>
          <table class="table">
            <tr>
              <td>
                <div id="favorites_buttons_<%= post.id %>">
                  <%= render partial: 'favorites/favorite', locals: {post: post} %>
                </div>
              </td>
              <td><%= post.comments.count %>コメント</td>
              <td>
                <%= link_to "詳細", post_path(post), class: 'btn btn-primary' %>
              </td>
            </tr>
          </table>
        </div>
      </div>
      <% end %>
    <% else %>
      <p class="nothing pl-5">投稿はありません</p>
    <% end %>
  </div>

app/views/posts/_new.html.erb
<!--記事投稿入力画面--->

<div class="form-container border rounded m-5">

  <%= form_with model: post, local: true do |f| %>

  <table class="table">
    <tr>
      <th></th>
      <td>
        <%= f.radio_button :category, :'捜索中' %>
        <%= f.label :category_捜索中, '捜索中' %>
        <%= f.radio_button :category, :'保護中' %>
        <%= f.label :category_保護中, '保護中' %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= f.radio_button :animal, :'犬' %>
        <%= f.label :animal_犬, '犬' %>
        <%= f.radio_button :animal, :'猫' %>
        <%= f.label :animal_猫, '猫' %>
        <%= f.radio_button :animal, :'その他' %>
        <%= f.label :animal_その他, 'その他' %>
      </td>
    </tr>
    <tr>
      <th>いなくなった・保護した 場所</th>
      <td>
        <%= f.text_field :plase, size: 40, placeholder: '○○県　○○市' %>
      </td>
    </tr>
    <tr>
      <th>写真 (複数選べます)</th>
      <td>
        <%= f.attachment_field :post_images_images, multiple: true %>
      </td>
    </tr>
    <tr>
      <th>名前</th>
      <td>
        <%= f.text_field :pet_name %>
      </td>
    </tr>
    <tr>
      <th>性別</th>
      <td>
        <%= f.radio_button :pet_sex, :'オス'%>
        <%= f.label :pet_sex, 'オス' %>
        <%= f.radio_button :pet_sex, :'メス' %>
        <%= f.label :pet_sex, 'メス' %>
        <%= f.radio_button :pet_sex, :'不明' %>
        <%= f.label :pet_sex, '不明' %>
      </td>
    </tr>
    <tr>
      <th>性格や特徴</th>
      <td>
        <%= f.text_area :text, size: "60x10", placeholder: '特徴や性格、様子などを書きましょう' %>
      </td>
    </tr>
    <tr>
      <th></th>
      <td>
        <%= f.submit '投稿', class: 'btn btn-primary m-5 w-25' %>
      </td>
    </tr>
  </table>
  <% end %>
</div>

app/views/posts/_retrieval.html.erb
<div class="search-form">
  <%= form_with url: retrieval_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% @post.errors.full_messages.each do |message| %>
  <div class="form-error">
     <%= message %>
  </div>
<% end %>

<h2 class="font p-3">投稿を編集</h2>
<div class="top-content pb-2">
  <%= link_to '削除', post_path(@post), class: 'btn btn-danger', method: :delete %>
</div>

<%= render 'posts/new', post: @post %>

app/views/posts/new.html.erb
<% @post.errors.full_messages.each do |message| %>
  <div class="form-error">
     <%= message %>
  </div>
<% end %>

<h2 class="font p-3">新しい投稿</h2>
<%= render 'posts/new', post: @post %>

app/views/posts/protect.html.erb
<div class="m-5">
  <div class="top-content pb-3">
    <%= render 'posts/retrieval', keyword: @keyword %>
    <%= link_to new_post_path, class: 'btn btn-light m-2' do %><i class="fas fa-plus-circle"> 投稿する</i><% end %>
  </div>

  <div class="container bg-white border rounded">
    <h3 class="title">保護投稿 一覧</h3>
    <%= render 'posts/list', posts: @posts %>
  </div>
</div>

app/views/posts/retrieval.erb
<div class="top-content mt-3">
  <%= render 'posts/retrieval', keyword: @keyword %>
  <%= link_to new_post_path, class: 'btn btn-light m-2' do %>
    <i class="fas fa-plus-circle"> 投稿する</i>
  <% end %>
</div>



<div class="cintainer p-5">
  <h2 class="font">検索結果 <span >"<%= @keyword %>"</span></h2>

  <!--検索結果-->
  <div class="bg-white border rounded w-100">
    <h3 class="border-bottom title">捜索投稿</h3>
    <%= render 'posts/list', posts: @search_posts %>
    <h3 class="border-bottom title">保護投稿</h3>
    <%= render 'posts/list', posts: @protect_posts %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="m-5">
  <div class="top-content pb-3">
    <%= render 'posts/retrieval', keyword: @keyword %>
    <%= link_to new_post_path, class: 'btn btn-light m-2' do %>
      <i class="fas fa-plus-circle"> 投稿する</i>
    <% end %>
  </div>
  
  <div class="container bg-white border rounded">
    <h3 class="title">捜索願い投稿 一覧</h3>
    <%= render 'posts/list', posts: @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<h3 class="font p-3">投稿の詳細</h3>

<div class="container mb-5">
  
    <div class="row">
      <div class="col-2">
        <%= render 'users/info', user: @post.user %>
      </div>
      <div class="col-10">
        <% if @post.post_images.present? %>
          <% @post.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, class: 'rounded', size: "200x200" %>
          <% end %>
        <% else %>
          <%= image_tag "logo.jpg" %>
        <% end %>
        
        
      <div class="mt-3 bg-white border rounded">
        <div class="top-content p-2">
          <% if @post.user == current_user %>
            <%= link_to '編集', edit_post_path(@post), class: 'btn btn-secondary' %>
            <%= link_to '削除', post_path(@post), class: 'btn btn-danger', method: :delete %>
          <% end %>
        </div>
        <table class="table">
          <tr>
            <th>投稿日</th>
            <td><%= @post.created_at.strftime('%Y年%m月%d日') %></td>
            <td id="favorites_buttons_<%= @post.id %>">
              <%= render 'favorites/favorite', post: @post %>
            </td>
          </tr>
          <tr>
            <th>場所</th>
            <td colspan="2"><%= @post.plase %></td>
          </tr>
          <tr>
            <th><%= @post.category %></th>
            <td colspan="2"><%= @post.animal %></td>
          </tr>
          <tr>
            <th>性別 </th>
            <td colspan="2"><%= @post.pet_sex %></td>
          </tr>
          <% if @post.pet_name.present? %>
            <tr>
              <th>名前 </th>
              <td colspan="2"><%= @post.pet_name %></td>
            </tr>
          <% end %>
          <tr>
            <th>特徴・説明</th>
            <td colspan="2"><%= @post.text %></td>
          </tr>
        </table>
      </div>
        
      <div class="mt-3 bg-white border rounded">
        <div id="comment_area">
          <%= render 'comments/comment', post: @post, comment: @comment %>
      </div>
    </div>
  </div>