config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :favorites
    end

    resource :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :chats, only: %i[index show create]

  resources :posts, only: %i[new show create destroy edit update] do
    resource :favorites, only: %i[index create destroy]
    resources :comments, only: %i[create destroy]
  end

  get 'retrieval' => 'posts#retrieval'

  get 'protect' => 'posts#protect'

  get 'search' => 'posts#search'
  # 通知
  resources :notifications, only: [:index]
  delete 'notifications/destroy' => 'notifications#destroy_all'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, inital-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/bb6cd5aa95.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag "logo.jpg" %></a>
          <!--ハンバーガーメニュー-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to search_path, class: 'nav-link text-dark' do %><i class="fas fa-paw">捜索願い一覧</i><% end %></li>
                <li class="nav-item"><%= link_to protect_path, class: 'nav-link text-dark' do %><i class="fas fa-hand-holding-medical">保護一覧</i><% end %></li>
                <li class="nav-item"><%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %><i class="fas fa-home">マイページ</i><% end %></li>

                <li class="nav-item"><%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %><i class="fas fa-sign-out-alt">ログアウト</i><% end %></li>
              <% else %>
                <li class="nav-item"><%= link_to search_path, class: 'nav-link text-dark' do %><i class="fas fa-paw">捜索願い一覧</i><% end %></li>
                <li class="nav-item"><%= link_to protect_path, class: 'nav-link text-dark' do %><i class="fas fa-hand-holding-medical">保護一覧</i><% end %></li>
                <li class="nav-item"><%= link_to new_user_registration_path, class: 'nav-link text-dark' do %><i class="fas fa-user-plus">新規登録</i><% end %></li>
                <li class="nav-item"><%= link_to new_user_session_path, class: 'nav-link text-dark' do %><i class="fas fa-sign-in-alt">ログイン</i><% end %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>
    <% if flash[:notice] %>
        <div class="flash">
             <%= flash[:notice] %>
        </div>
    <% end %>


    <main class="main bg-white">

      <%= yield %>

    </main>
    <footer class="p-3 bg-dark text-white">
      <div class="footer_main">
        <p>© 2021 yama</p>
      </div>
    </footer>
  </body>
</html>